---
abstract: 'Intelligently distribute messages over time'
author:
  - 'Dana M. Diederich <dana@realms.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Message-Inform
requires:
  Carp: 0
  Data::Dumper: 0
  Message::Match: 0
  Message::Transform: 0
  Storable: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dana/perl-Message-Inform/issues
  homepage: https://github.com/dana/perl-Message-Inform
  repository: https://github.com/dana/perl-Message-Inform.git
version: 1.132270
